version: '3.8'

services:
  api-dev:
    build: 
      context: .
      target: development
    ports:
      - "3333:3333"
    environment:
      - PORT=3333
    volumes:
    - .:/app
    - /app/node_modules

    command: npm run start:watch